export const biographies = [
  {
    id: '2022-02',
    startDate: '2022年2月',
    belongs: 'フリーランス',
    role: 'フロントエンドエンジニア',
    detail: 'webサイトやwebアプリの制作に携わっています。',
    skills: ['JavaScript', 'React', 'Next.js', 'Git'],
  },
  {
    id: '2021-09',
    startDate: '2021年9月',
    endDate: '2022年1月',
    belongs: '制作会社',
    role: 'フロントエンドエンジニア',
    detail:
      'コーディングだけでなく、フロントエンド業務全般の管理、技術ディレクション、技術サポートなどを行ってます。案件としては、コーポレート、教育機関、リクルート、キャンペーンなどのwebサイトや社内システムなどのwebアプリの制作に携わりました。',
    skills: [
      'EJS',
      'Pug',
      'Sass',
      'JavaScript',
      'React',
      'gulp',
      'webpack',
      'Storybook',
      'Git',
    ],
  },
  {
    id: '2020-04',
    startDate: '2020年4月',
    endDate: '2021年8月',
    belongs: '制作会社',
    role: 'フロントエンドエンジニア',
    detail:
      '受託開発で業務支援ツールの開発をしたり、コーポレートサイトやアーティストサイトのコーディングをしました。',
    skills: [
      'React',
      'EJS',
      'Sass',
      'JavaScript',
      'TypeScript',
      'gulp',
      'webpack',
      'Git',
      'リモートワーク',
      'API設計',
    ],
  },
  {
    id: '2016-10',
    startDate: '2016年10月',
    endDate: '2020年3月',
    belongs: 'スタートアップ',
    role: 'フロントエンドエンジニア',
    detail:
      '自社開発の業務支援ツールのフロントエンド開発やプロダクトサイトのコーディングをしました。',
    skills: [
      'Angular(1.x)',
      'React',
      'Sass',
      'jQuery',
      'WordPress',
      'gulp',
      'webpack',
      'Git',
      'リモートワーク',
    ],
  },
  {
    id: '2015-08',
    startDate: '2015年7月',
    endDate: '2016年9月',
    belongs: '制作会社',
    role: 'マークアップエンジニア',
    detail:
      '大手のコーポレートサイトや会員制サービスサイトから、大学入試サイト、ECサイト、スマホゲームなど幅広い案件のコーディングを経験しました。',
    skills: ['HTML', 'EJS', 'CSS', 'Sass', 'JavaScript', 'jQuery', 'gulp'],
  },
  {
    id: '2014-06',
    startDate: '2014年6月',
    endDate: '2015年6月',
    belongs: 'webサービス会社',
    role: 'デザイナー',
    detail:
      'サービスの新規会員やアクティブユーザーの獲得、有料会員への誘導方法などを考えるなどの、サービスの改善に携わりました。業務内容はデザイナーというよりディレクションに近いです。',
    skills: ['画面設計', '解析', 'HTML', 'CSS', 'Sass'],
  },
  {
    id: '2013-03',
    startDate: '2013年3月',
    endDate: '2013年10月',
    belongs: '広告媒体社',
    role: '営業',
  },
  {
    id: '2011-04',
    startDate: '2011年4月',
    endDate: '2013年2月',
    belongs: '証券会社',
    role: '営業',
  },
]
